# Generated by Django 5.2.6 on 2025-10-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='images',
            new_name='image',
        ),
    ]
