# Generated by Django 5.2.6 on 2025-11-18 07:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='note',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnails'),
        ),
    ]
